---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yaneuayp/public_html/
    - /bin/cp -r * $DEPLOYPATH

---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yaneuayp/public_html/app
    - /bin/cp /build/* $DEPLOYPATH