name:  Deploy to Namecheap

on:
  push:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
    
    - name: Build project
      uses: npm run build

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.7
      with: 
        host: yanelyontheinternet.com
        username: ${{ secrets.CPANEL_USERNAME }}
        key: ${{ secrets.CPANEL.SSH_KEY }}
        port: 22
        source: "build/"
        target: "/home/yanelya/public_html/"