---
name: Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 23.x
      uses: actions/setup-node@v4
      with:
        node-version: '23.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: CI=false npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.CPANEL_IP }}
        username: ${{ secrets.CPANEL_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 21098
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }} 
        source: "build/"
        target: "/home/${{ secrets.CPANEL_USERNAME }}/public_html/"
        script: |
          echo "✅ Deploying build..."
          
          # Add a unique timestamp file during deployment
          echo "Deployed at $(date)" > build/deployment.txt

          # Upload the build with the timestamp file
          rsync -avz --progress build/ /home/${{ secrets.CPANEL_USERNAME }}/public_html/

          # Verify the unique file was uploaded
          ls -la /home/${{ secrets.CPANEL_USERNAME }}/public_html/deployment.txt
